baseURL = "/"
languageCode = "en-us"
title = "ElsaCP - Easy Linux Server Administration Control Panel"
description = "ElsaCP is Simplified Open Source Linux Control Panel"
author = "Aris Ripandi"
theme = "kube"

disableHugoGeneratorInject = true
canonifyURLs = true
enableRobotsTXT = true
googleAnalytics = "UA-113965807-1"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  noindex_kinds = [
    "taxonomy",
    "taxonomyTerm"
  ]

Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "Aris Ripandi" # add your company name
  github = "elsacp" # add your github profile name
  twitter = "elsacp" # add your twitter profile
  email = "elsacp@protonmail.com"

[[menu.main]]
    name = "Features"
    weight = -200
    url = "#features"
[[menu.main]]
    name = "Install"
    weight = -200
    url = "/docs/install"
[[menu.main]]
    name = "Docs"
    weight = -100
    url = "/docs/"
[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/blog/"
[[menu.main]]
    name = "FAQs"
    weight = -100
    url = "/faq/"
